## Ensemble Methods
### This is the notebook for the Ensemble Methods project

In [1]:
import numpy as np

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import VotingClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

from sklearn.linear_model import LinearRegression

from sklearn.neighbors import KNeighborsRegressor

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import VotingRegressor

from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestClassifier

### Load Data

In [28]:
data1 = pd.read_csv("APMM10-clf-dataset02.csv")

In [29]:
data1

,X1,X2,y
0,-0.665227,-0.161289,0
1,1.747817,-0.054035,0
2,0.792945,0.687195,1
3,0.533777,-1.436711,0
4,0.841554,0.912889,1
...,...,...,...
995,0.733894,0.816094,1
996,-0.912319,-0.730586,0
997,1.693724,-0.854750,0
998,0.613573,-0.967509,0


In [30]:
X = data1[["X1", "X2"]]

In [31]:
y = data1.y.ravel()

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [33]:
# KNeighborsClassifier() with K=3
knn3 = KNeighborsClassifier(n_neighbors=3)
# KNeighborsClassifier() with K=4
knn4 = KNeighborsClassifier(n_neighbors=4)
# KNeighborsClassifier() with K=5
knn5 = KNeighborsClassifier(n_neighbors=5)
# DecisionTreeClassifier() with max_depth=3
dct3 = DecisionTreeClassifier(max_depth=3)
# DecisionTreeClassifier() with max_depth=4
dct4 = DecisionTreeClassifier(max_depth=4)

In [34]:
voting_clf = VotingClassifier(
    estimators=[('knn3', knn3), ('knn4', knn4), ('knn5', knn5),
               ('dct3', dct3), ('dct4', dct4)],
    voting='hard'  # or 'soft' if you want to average predicted probabilities
)

In [35]:
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('knn3', KNeighborsClassifier(n_neighbors=3)),
                             ('knn4', KNeighborsClassifier(n_neighbors=4)),
                             ('knn5', KNeighborsClassifier()),
                             ('dct3', DecisionTreeClassifier(max_depth=3)),
                             ('dct4', DecisionTreeClassifier(max_depth=4))])

In [36]:
y_pred = voting_clf.predict(X_test)

In [37]:
accuracy = accuracy_score(y_pred, y_test)

In [38]:
accuracy

0.82

In [41]:
f1 = f1_score(y_test, y_pred)

In [42]:
f1

0.6715328467153285

In [45]:
for name, vc in voting_clf.named_estimators_.items():
    y_pred = vc.predict(X_test)
    
    # Calculate precision
    precision = precision_score(y_test, y_pred)  # or 'macro'/'micro' if you prefer
    recall = recall_score(y_test, y_pred)
    print(f"{name}: Precision Score = {precision:.4f}")
    print(f"{name}: Recall Score = {recall:.4f}")

knn3: Precision Score = 0.7164
knn3: Recall Score = 0.6154
knn4: Precision Score = 0.8000
knn4: Recall Score = 0.5641
knn5: Precision Score = 0.7460
knn5: Recall Score = 0.6026
dct3: Precision Score = 0.8235
dct3: Recall Score = 0.5385
dct4: Precision Score = 0.8077
dct4: Recall Score = 0.5385


### Load Dataset 3

In [112]:
data2 = pd.read_csv("APMM10-reg-dataset03.csv")

In [17]:
data2.head()

,X1,X2,X3,X4,X5,y
0,-0.735201,1.798725,-1.095519,1.656208,-0.880754,238.538453
1,-1.613561,-1.371901,-0.172946,1.471170,1.711708,110.789713
2,0.651391,0.954002,0.570891,-0.315269,1.135566,161.445075
3,-1.350556,-0.687014,-0.475795,-0.075871,-0.826112,68.424239
4,1.554160,0.342338,-0.530971,0.853976,-0.335138,119.032776


In [43]:
# LinearRegression()
lr = LinearRegression()
# KNeighborsRegressor() with K=5
knr5 = KNeighborsRegressor(n_neighbors=5)
# DecisionTreeRegressor() with max_depth=5
dtr5 = DecisionTreeRegressor(max_depth=5)

In [44]:
voting_reg = VotingRegressor(
        estimators=[('lr', lr), ('knr5', knr5), ('dtr5', dtr5)])

In [45]:
X2 = data2.drop(columns=["y"]).copy()

In [46]:
y2 = data2.y.ravel()

In [47]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.25, random_state=42)

In [48]:
voting_reg.fit(X_train2, y_train2)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('knr5', KNeighborsRegressor()),
                            ('dtr5', DecisionTreeRegressor(max_depth=5))])

In [49]:
y_pred2 = voting_reg.predict(X_test2)

In [52]:
rsme = np.sqrt(mean_squared_error(y_pred2, y_test2))

In [53]:
rsme

42.69434330908632

In [54]:
for name, vc in voting_reg.named_estimators_.items():
    y_pred2 = vc.predict(X_test2)

    rsme = np.sqrt(mean_squared_error(y_pred2, y_test2))
    print(f"{name}: RSME Value: {rsme}")

lr: RSME Value: 39.495311947060166
knr5: RSME Value: 48.36226892861553
dtr5: RSME Value: 48.007567952184814


### Load Dataset

In [43]:
data3 = pd.read_csv("APMM10-clf-dataset04.csv")

In [44]:
data3.head()

,X1,X2,X3,X4,X5,y
0,1.555730,0.628147,-0.567278,-2.548786,-1.575909,2
1,-1.760054,-0.417340,0.353626,2.383121,0.172636,0
2,-0.329064,-0.461760,-1.183120,1.436410,-1.228790,0
3,-1.801581,0.075704,1.623614,1.218431,1.051731,0
4,0.543973,-0.595228,-1.202407,0.872089,0.185406,0


In [45]:
data3.y.value_counts()

y
0    696
1    199
2    105
Name: count, dtype: int64

In [46]:
# Build  a random forest classifier with 100 estimators (and random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [47]:
X3 = data3.drop(columns=["y"]).copy()

In [48]:
y3 = data3.y.ravel()

In [49]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.3, random_state=42, stratify=y3)

In [50]:
rf.fit(X_train3, y_train3)

RandomForestClassifier(random_state=42)

In [51]:
y_pred3 = rf.predict(X_test3)

In [52]:
accuracy = accuracy_score(y_test3, y_pred3)

In [53]:
accuracy

0.9033333333333333

In [65]:
f1s3 = f1_score(y_test3, y_pred3, average='weighted')

In [67]:
f1s3

0.8995536562203229

In [59]:
cm = confusion_matrix(y_test3, y_pred3)
cm.shape

(3, 3)

In [68]:
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[203   5   1]
 [  8  49   3]
 [  9   3  19]]


## Advanced Ensemble Methods

In [69]:
from sklearn.ensemble import AdaBoostClassifier

In [95]:
stump = DecisionTreeClassifier(max_depth=1, random_state=42)

In [96]:
ada = AdaBoostClassifier(estimator=stump, n_estimators=60, learning_rate=1.0, random_state=42)

In [97]:
data4 = pd.read_csv("APMM10-clf-dataset01.csv")

In [98]:
data4.y.value_counts()

y
0    250
1    250
Name: count, dtype: int64

In [99]:
data4.head()

,X1,X2,y
0,0.360289,0.907079,0
1,0.487743,-0.293079,1
2,0.802645,0.452520,0
3,1.021270,-0.503749,1
4,1.134119,0.011527,0


In [100]:
X4 = data4.drop(columns=["y"]).copy()

In [101]:
y4 = data4.y.ravel()

In [102]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=.30, random_state=42, stratify=y4)

In [103]:
ada.fit(X_train4, y_train4)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1,
                                                    random_state=42),
                   n_estimators=60, random_state=42)

In [104]:
y_pred4 = ada.predict(X_test4)

In [105]:
accuracy4 = accuracy_score(y_test4, y_pred4)

In [106]:
accuracy4

0.96

In [108]:
f1s4 = f1_score(y_test4, y_pred4, average='weighted')

In [113]:
f1s4

0.9599928876244664

In [114]:
stump.fit(X_train4, y_train4)

DecisionTreeClassifier(max_depth=1, random_state=42)

In [115]:
y_pred_stump = stump.predict(X_test4)

In [117]:
precision4 = precision_score(y_test4, y_pred_stump, average='weighted')

In [118]:
precision4

0.7805145046524357

In [119]:
recall4 = recall_score(y_test4, y_pred_stump, average='weighted')

In [120]:
recall4

0.7733333333333333

### Load Dataset

In [136]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

In [137]:
data5 = pd.read_csv("APMM10-clf-dataset08.csv")

In [139]:
data5.y.value_counts()

y
0    321
1    179
Name: count, dtype: int64

In [140]:
X5 = data5.drop(columns=["y"]).copy()

In [141]:
y5 = data5.y.ravel()

In [142]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=.30, random_state=42, stratify=y5)

In [143]:
# LogisticRegression() with a max_iter limit of 1000,
lr = LogisticRegression(max_iter=1000)
# DecisionTreeClassifier() with a max_depth of 3 (and random_state=42),
dtc3 = DecisionTreeClassifier(max_depth=3, random_state=42)
# DecisionTreeClassifier() with a max_depth of 5 (and random_state=42)
dtc5 = DecisionTreeClassifier(max_depth=5, random_state=42)
# KNeighborsClassifier() with k=5, and
knn5 = KNeighborsClassifier(n_neighbors=5)
# KNeighborsClassifier() with k=7
knn7 = KNeighborsClassifier(n_neighbors=7)

In [144]:
stack = StackingClassifier(
            estimators=[('dtc3', dtc3), ('dtc5', dtc5), ('knn5', knn5), ('knn7', knn7), ('lr', lr)],
            final_estimator=LogisticRegression(),
            cv=5
)

In [145]:
stack.fit(X_train5, y_train5)

StackingClassifier(cv=5,
                   estimators=[('dtc3',
                                DecisionTreeClassifier(max_depth=3,
                                                       random_state=42)),
                               ('dtc5',
                                DecisionTreeClassifier(max_depth=5,
                                                       random_state=42)),
                               ('knn5', KNeighborsClassifier()),
                               ('knn7', KNeighborsClassifier(n_neighbors=7)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression())

In [146]:
y_pred5 = stack.predict(X_test5)

In [147]:
accuracy5 = accuracy_score(y_test5, y_pred5)

In [148]:
accuracy5

0.96

In [149]:
f1s5 = f1_score(y_test5, y_pred5, average='weighted')

In [150]:
f1s5

0.9598288270764442

In [152]:
for name, vc in stack.named_estimators_.items():
    y_pred5 = vc.predict(X_test5)
    
    # Calculate precision
    precision = precision_score(y_test5, y_pred5, average='weighted')  # or 'macro'/'micro' if you prefer
    recall = recall_score(y_test5, y_pred5, average='weighted')
    print(f"{name}: Precision Score = {precision:.4f}")
    print(f"{name}: Recall Score = {recall:.4f}")

dtc3: Precision Score = 0.9536
dtc3: Recall Score = 0.9533
dtc5: Precision Score = 0.9136
dtc5: Recall Score = 0.9133
knn5: Precision Score = 0.9472
knn5: Recall Score = 0.9467
knn7: Precision Score = 0.9486
knn7: Recall Score = 0.9467
lr: Precision Score = 0.8859
lr: Recall Score = 0.8867
