## CMPINF 2105 Math and Stats
### Pen and Paper Homework Module 1 and 2
### Import Modules

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot
import sympy

#### Question 1: Given vectors a and b, what is a+b, a-b, 2a-2b?

In [39]:
a = sympy.Matrix(
    [
        [2], [-1]
    ]
)
a

Matrix([
[ 2],
[-1]])

In [41]:
b = sympy.Matrix(
    [
        [-3], [4]
    ]
)
b

Matrix([
[-3],
[ 4]])

In [46]:
a+b

Matrix([
[-1],
[ 3]])

In [47]:
a-b

Matrix([
[ 5],
[-5]])

In [48]:
2*a-2*b

Matrix([
[ 10],
[-10]])

#### Question 2: Find the dot product of vectors c and d

In [49]:
c = sympy.Matrix(
    [
        [6], [0], [-2]
    ]
)
c

Matrix([
[ 6],
[ 0],
[-2]])

In [50]:
d = sympy.Matrix(
    [
        [-1], [4], [-1]
    ]
)
d

Matrix([
[-1],
[ 4],
[-1]])

In [52]:
c.dot(d)

-4

#### Question 3: The sum of matrix M + matrix N

In [54]:
M = sympy.Matrix(
    [
        [2, 3], [5, -1]
    ]
)
M

Matrix([
[2,  3],
[5, -1]])

In [55]:
N = sympy.Matrix(
    [
        [1, 0], [-3, 4]
    ]
)
N

Matrix([
[ 1, 0],
[-3, 4]])

In [56]:
M+N

Matrix([
[3, 3],
[2, 3]])

#### Question 4: Calculate 3 times the matrix P

In [58]:
P = sympy.Matrix(
    [
        [7, -2], [-6, 3]
    ]
)
P

Matrix([
[ 7, -2],
[-6,  3]])

In [59]:
3*P

Matrix([
[ 21, -6],
[-18,  9]])

#### Question 5: Find the product of a matrix A with vector b

In [60]:
A = sympy.Matrix(
    [
        [2, 1], [-1, 3]
    ]
)
A

Matrix([
[ 2, 1],
[-1, 3]])

In [61]:
B = sympy.Matrix(
    [
        [3], [-1]
    ]
)
B

Matrix([
[ 3],
[-1]])

In [63]:
A@B

Matrix([
[ 5],
[-6]])

#### Question 6: Take the matrix dot product of two matrices A and B

In [64]:
A = sympy.Matrix(
    [
        [1, 2], [3, 4]
    ]
)
A

Matrix([
[1, 2],
[3, 4]])

In [65]:
B = sympy.Matrix(
    [
        [-1, 3], [4, -2]
    ]
)
B

Matrix([
[-1,  3],
[ 4, -2]])

In [66]:
A@B

Matrix([
[ 7, -1],
[13,  1]])

#### Question 7: Find the eigenvalues, vectors of matrix M

In [71]:
M = sympy.Matrix(
    [
        [2, 1], [1, 2]
    ]
)
M

Matrix([
[2, 1],
[1, 2]])

In [72]:
Mh = np.array(
    [
        [2, 1], [1, 2]
    ]
)
Mh

array([[2, 1],
       [1, 2]])

In [73]:
eigval, eigvect = np.linalg.eig(Mh)

In [74]:
eigval

array([3., 1.])

In [75]:
eigvect

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [76]:
M.eigenvals()

{3: 1, 1: 1}

In [77]:
M.eigenvects()

[(1,
  1,
  [Matrix([
   [-1],
   [ 1]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1]])])]

#### Question 8: Solve the linear system of equations

In [79]:
lol = sympy.Matrix(
    [
        [3, 5], [7, 2]
    ]
)
lol

Matrix([
[3, 5],
[7, 2]])

In [89]:
ok = sympy.Matrix(
    [
        [59], [99]
    ]
)
ok

Matrix([
[59],
[99]])

In [90]:
lol.det()

-29

In [88]:
sympy.Matrix.solve_least_squares(lol, ok)

Matrix([
[13],
[ 4]])

#### Question 9: Solve the linear system of equations

In [85]:
pip = sympy.Matrix(
    [
        [9, 9, -7], [3, -2, -9], [6, 0, 1]
    ]
)
pip

Matrix([
[9,  9, -7],
[3, -2, -9],
[6,  0,  1]])

In [86]:
nana = sympy.Matrix(
    [
        [6], [3], [-10]
    ]
)
nana

Matrix([
[  6],
[  3],
[-10]])

In [87]:
sympy.Matrix.solve_least_squares(pip, nana)

Matrix([
[-911/615],
[ 263/205],
[-228/205]])

#### Question 10: Solve the linear system of equations

In [91]:
meel = sympy.Matrix(
    [
        [11, 3, 9], [5, 4, 2], [37, 18, 24]
    ]
)
meel

Matrix([
[11,  3,  9],
[ 5,  4,  2],
[37, 18, 24]])

In [92]:
ces = sympy.Matrix(
    [
        [237], [101], [-777]
    ]
)
ces

Matrix([
[ 237],
[ 101],
[-777]])

In [93]:
sympy.Matrix.solve_least_squares(meel, ces)

TypeError: Matrix must be non-singular.

There is no solution to this linear system of equations.