## CMPINF 2100 Week 03

## Introduction to 2D NumPy Arrays

We saw how to create, manipulate, modify, organize, and summarize 1D arrays, but what does 1D even mean?

### Import NumPY

In [1]:
import numpy as np

## Lists of lists

Return back to base Python to being, wehave made lists of lists before...

But this list of lists will be simple, just 2 elements. Each element will be a list of 3 values.

In [2]:
[ [0 ,0 ,0], [1, 1, 1] ]

[[0, 0, 0], [1, 1, 1]]

Do the same thing above but let's include in more white space and spacing!!!

In [3]:
[ [0, 0, 0],
  [1, 1, 1]]

[[0, 0, 0], [1, 1, 1]]

In [5]:
np.array([ [0, 0, 0, 0, 0, 0],
  [1, 1, 1, 1, 1, 1]]).ndim

2

Let's assign our list of lists to an object

In [6]:
my_list_of_lists = [ [0, 0, 0], 
                     [1, 1, 1]]

Let's convert the list of lists to a NumPy array!!!

In [7]:
my_array = np.array(my_list_of_lists)

In [9]:
my_array.ndim

2

In [10]:
my_array.shape

(2, 3)

In [11]:
my_array.size

6

2D arrays are MATRICES and they kind of look like TABLES!!

2D arrays have 2 dimensions...they have ROWS and COLUMNS!!!

But please remember the list of lists does NOT understand ROWS and COLUMNS.

Creating a 2D array from a list of lists required each inner list to have the same length!!

In [12]:
np.array([ [0,0,0],
          [1,1,1,1,1,1,1,1,1,1,1]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Alternatively, we can create 2D arrays by COMBINING 1D arrays!!!

In [13]:
a = np.zeros(3)

In [14]:
b = np.ones(3)

In [15]:
a.ndim

1

In [16]:
a.shape

(3,)

In [17]:
a.size

3

In [18]:
b.ndim

1

In [19]:
b.shape

(3,)

In [20]:
b.size

3

We can use the `np.concatenate()` function to combine the two 1D arrays.

In [21]:
np.concatenate([a,b])

array([0., 0., 0., 1., 1., 1.])

Creating a 2D array from 1D arrays requires us to change the syntax to `np.concatenate()`

In [22]:
np.concatenate([ [a], [b]])

array([[0., 0., 0.],
       [1., 1., 1.]])

There are speciality functions that simplify STACKING arrays together!!!


Stacking arrays ON top of each other is known as VERTICAL stacking or VERTICAL combining.

In [23]:
np.vstack([a,b])

array([[0., 0., 0.],
       [1., 1., 1.]])

Combining arrays side by side is known as HORIZONTAL stacking.

In [25]:
np.hstack([a,b])

array([0., 0., 0., 1., 1., 1.])

We can combine or stack more than 2 arrays at the same time!

In [26]:
c = 2*np.ones(3)

In [27]:
d = 3*np.ones(3)

In [28]:
c

array([2., 2., 2.])

In [29]:
d

array([3., 3., 3.])

In [30]:
np.vstack([a,b,c,d])

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [32]:
np.vstack([a,b,c,d]).shape

(4, 3)

We can also stack 2D arrays together!!!

In [33]:
np.vstack([np.vstack([a,b]), np.vstack([c,d]) ])

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])