## CMPINF 2100 Week 03

### Introduction to 1D NumPy Arrays

NumPy is what allowed Python to do any kind of Data Analysis.

NumPy is a module and so we NEED to import NumPy in order to use any of its objects, functions, or data types.

In [2]:
import numpy as np

In [4]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Ap<...>kages/numpy/__init__.py'>


## NumPy 1D Arrays

The **ndarray** is the work hourse of NumPy. We will start with the simplest version known as a 1D array.

## Creating 1D arrays

In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
range(6)

range(0, 6)

In [8]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [17]:
a = np.arange(6)

In [18]:
type(a)

numpy.ndarray

In [12]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
np         module     <module 'numpy' from '/Ap<...>kages/numpy/__init__.py'>


In [13]:
a_list = list(range(6))

In [14]:
dir(a_list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [16]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

BUT...one thing that is SIMILAR between lists and NumPy arrays is that we can SLICE/INDEX both objects!!

In [19]:
a_list[0]

0

In [20]:
a[0]

0

In [21]:
a_list[:3]

[0, 1, 2]

In [22]:
a[:3]

array([0, 1, 2])

### Attributes

In [24]:
len(a_list)

6

But with numpy array, we can instead use ATTRIBUTES to identify the NUMBER of dimensions, the number of elements per dimension, and the total SIZE in the array.

In [23]:
a.ndim

1

In [24]:
a.shape

(6,)

In [25]:
type(a.shape)

tuple

In [26]:
a.size 

6

In [27]:
help (a.shape)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |

### Other ways to create arrays

One way to make an array is with the `np.array()` function. This lets us CONVERT a LIST or TUPLE to an array.

In [28]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [28]:
cesar = np.array([(1,2), (1,2)])

In [30]:
cesar.ndim

2

In [32]:
cesar.shape

(2, 2)

In [33]:
cesar.size

4

In [30]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [31]:
a1 = np.array([1, 2, 3, 4, 5])

In [34]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
a1         ndarray    5: 5 elems, type `int64`, 40 bytes
a_list     list       n=6
np         module     <module 'numpy' from '/Ap<...>kages/numpy/__init__.py'>


In [35]:
a1.ndim

1

In [36]:
a1.shape

(5,)

In [37]:
a1.size

5

In [39]:
a2 = np.array((1, 2, 3, 4, 5))

In [40]:
a2

array([1, 2, 3, 4, 5])

In [41]:
a1 == a2

array([ True,  True,  True,  True,  True])

There are specialty functions for creating arrays of 1 value.

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
0 * np.arange(5)

array([0, 0, 0, 0, 0])

The `np_arange()` function has 3 arguments.

START, STOP (EXCLUSIVE), and STEP.

In [36]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [47]:
np.arange(0, 6, 3)

array([0, 3])

In [40]:
np.arange(0, 7, 3)

array([0, 3, 6])

In [39]:
np.arange(0, 6+1, 2)

array([0, 2, 4, 6])

In [37]:
np.arange(0, 100+1, 20)

array([  0,  20,  40,  60,  80, 100])

THE `np.linspace()` function is very similar to `np.arange()` BUT

START, STOP (INCLUSIVE) and Number of points (number of intervals).

In [41]:
np.linspace(0, 6, num=1)

array([0.])

In [42]:
np.linspace(0, 6, num=6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [43]:
np.linspace(0, 6, num=7)

array([0., 1., 2., 3., 4., 5., 6.])

In [45]:
np.arange(-10, 10, 1.2)

array([-10. ,  -8.8,  -7.6,  -6.4,  -5.2,  -4. ,  -2.8,  -1.6,  -0.4,
         0.8,   2. ,   3.2,   4.4,   5.6,   6.8,   8. ,   9.2])

In [46]:
np.arange(-10, 10, 1.2).shape

(17,)

In [47]:
np.linspace(-10,10, num=17)

array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ,  -3.75,  -2.5 ,  -1.25,
         0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,
        10.  ])

In [48]:
np.linspace(-10,10, num=17).shape

(17,)

## Differences with lists

Operators may behave differently on NumPys arrays compared to lists.

In [49]:
a_list

[0, 1, 2, 3, 4, 5]

In [50]:
a_list == [0, 1, 2, 3, 4, 5]

True

In [51]:
a == np.array([0, 1, 2, 3, 4, 5])

array([ True,  True,  True,  True,  True,  True])

In [52]:
a == np.array([10, 1, 2, 3, 4, 5])

array([False,  True,  True,  True,  True,  True])

In [55]:
np.zeros(5) == np.zeros(10)

/var/folders/hn/_r1c754d1kj1fxryljd8w6g80000gn/T/ipykernel_91760/506179799.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.zeros(5) == np.zeros(10)


False

In [57]:
np.array_equal(a, np.array([0,1, 2, 3, 4, 5]))

True

The `+` operator behaves differently!!!

In [58]:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [59]:
np.array([1, 2, 3]) + np.array([1, 2, 3])

array([2, 4, 6])