## CMPINF 2100 Week 04
### RESHAPING with NumPy
We need to review DIMENSIONS or SHAPES in NumPy. What is the difference between ROWS and COLUMNS?

## Import Modules

In [1]:
import numpy as np

## Introduction to reshaping
Lets being by reviewing a 1D NumPy array.

In [2]:
np.arange(1, 25 )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(1, 25).ndim

1

In [5]:
np.arange(1, 25).shape

(24,)

In [6]:
np.arange(1, 25).size

24

In [7]:
x = np.arange(1, 25)

In [8]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/Ap<...>kages/numpy/__init__.py'>
x          ndarray    24: 24 elems, type `int64`, 192 bytes


In [9]:
x.ndim

1

In [10]:
x.shape

(24,)

In [11]:
x.size

24

Let's convert or **RESHAPE** the 1D array into a 2D array!!!

We will literally ADD a dimension to the object and modify where and how they values are stored!!!

We reshape with the `.reshape()` method. All NumPy arrays have this method.

`.reshape(<NEW ROWS>, <NEW COLUMNS>)`

Let's convert the `x` into a 2D array with 12 rows and 2 columns.

In [12]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
x.reshape(12, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [14]:
[[1, 2], [3, 4] ] 

[[1, 2], [3, 4]]

In [16]:
x.reshape(12, 2).ndim

2

In [17]:
x.reshape(12, 2).shape

(12, 2)

In [18]:
x.reshape(12, 2).size

24

The `.ndim` attribute is DIFFERENT AFTER applying the reshaping operation! Originally, the `x` object has 1 dimension:

In [19]:
x.ndim

1

In [20]:
x.shape

(24,)

In [21]:
x.size

24

HOWEVER...VERY IMPORTANTLY, THE TOTAL number of elements has NOT CHANGED!!

We have just organized the data, not changed the items.

In [32]:
x2 = x.reshape(12, 2)

Of course, we could have reshaped to something other than 12 rows!!

We could have reshaped to 6 rows and 4 columns!!

In [36]:
x.reshape(6, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [37]:
x.reshape(4, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [38]:
x.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

I could even try 8 rows and 3 columns!!

In [39]:
x.reshape(8, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [40]:
x.reshape(3, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

The important point is that the NUMBER of ROWS multiplied by the NUMBER OF COLUMNS must equal the total number of ELEMENTS or SIZE!

If you don't want to do the mental math and type both the NEW NUMBER OF ROWS and the NEW number of COLUMNS.. you can include a -1 as an argument.

In [47]:
x.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
x.reshape(-1, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

PLEASE BE CAREFUL!!!

In [49]:
x.reshape(9, -1)

ValueError: cannot reshape array of size 24 into shape (9,newaxis)

In [50]:
x.reshape(9,3)

ValueError: cannot reshape array of size 24 into shape (9,3)

In [51]:
x.reshape(9, 2)

ValueError: cannot reshape array of size 24 into shape (9,2)

The SIZE must equal the PRODUCT of the number of rows and columns!

## Other reshaping procedures

The most common reshaping technique is the TRANSPOSE of a 2D array.

Transposing swaps the rows and columns!

To see how transposing works, lets work with a 2D array named `y`.

In [52]:
y = np.arange(1,25).reshape(8,-1)

In [53]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [54]:
y.ndim

2

In [55]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/Ap<...>kages/numpy/__init__.py'>
x          ndarray    24: 24 elems, type `int64`, 192 bytes
x2         ndarray    12x2: 24 elems, type `int64`, 192 bytes
x3         ndarray    12x2: 24 elems, type `int64`, 192 bytes
y          ndarray    8x3: 24 elems, type `int64`, 192 bytes


NumPy 2D arrays include the `.T` attribute to EXECUTE a transpose.

In [57]:
y.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23],
       [ 3,  6,  9, 12, 15, 18, 21, 24]])

In [58]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [59]:
y.shape

(8, 3)

In [60]:
y.T.shape

(3, 8)

Transposing is unfortunately what a lot of ppl will think of when you say RESHAPING the array!!

But the `.reshape()` method is FAR MORE GENERAL than TRANSPOSING!!

In [61]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [62]:
y.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23],
       [ 3,  6,  9, 12, 15, 18, 21, 24]])

In [63]:
y.reshape(12,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In fact, the `reshape()` function is so general we can turn a 2D array into a SINGLE ROW or SINGLE COLUMNS object!!!

In [64]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [65]:
y.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
y.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [67]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [68]:
y.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

But later in the semester and especially in the classes that follow CMPINF 2100...the difference between a TRUE 1D array and a 2D array that is a single column/row will be important...

Sometimes we need to DROP a 2D array into a 1D array.

We can do that with the `.ravel()` method.

In [69]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [70]:
x.ndim

1

In [71]:
y.reshape(1, -1).shape

(1, 24)

In [72]:
y.reshape(1, -1).ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [73]:
y.reshape(1, -1).ravel().ndim

1

## Summary

We need to pay attention to the num of ROWS and COLUMNS or the DIMENSIONS and SHAPE of the NumPy array!!

We can modify the SHAPE by `.shape()` and we can "SQUEEZE" or "compress" a 2D array into a 1D array with `.ravel()`.